### ISSUE TITLE
Enable the interface definitions to include the OCF design pattern

### ISSUE THREAD

**Issue by mjkoster** [core-wg/interfaces#2]
In OCF, Interfaces denoted by the "if" link target attribute are used to indicate one or more interfaces offered by a complex resource. The client may include "if" as a query parameter to control the returned representation content. OCF also uses "if" to control read/write permission to elements of a complex resource.

I believe we can use our collection examples to describe additional uses of the "if" attribute that are consistent with the OCF design patterns, by allowing multiple "if" values in links and queries, and enabling "if" query options to select items in a collection.

**Comment by bsilverajan** [comment]
After discussions with @mjkoster and @Julian-ZJT we decided to close this issue and re-open it if interest arises
